trigger:
  - main

pool:
  name: 'name'

steps:
  - checkout: self
    displayName: 'Checkout Code from GitHub'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'
      javaHomeOption: 'Path'
      jdkDirectory: 'C:\\Program Files\\Java\\jdk-17'
    displayName: 'Build and Run Unit Tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
      testResultsFormat: 'JUnit'
      failTaskOnMissingResultsFile: true
    displayName: 'Publish Maven Test Results'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'target'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'
